### ISSUE TITLE
Detalhes e correções

### ISSUE THREAD

**Issue by germanyn** [PauloGascho/cleanarch-crud#1]
1 - Recomendação utilizar sempre o parâmetro de referência como primeiro parâmetro, no caso id do usuário e aí o objeto de update
https://github.com/PauloGascho/cleanarch-crud/blob/5601b3b3fbe2f887023ac415e6759f190d512604/usecases/src/main/java/br/com/almode/cleanarch/usecases/adapters/usuario/UsuarioPersistenceAdapter.java#L18

2 - Tua rota de `get` por id não retorna 404 quando informa um id inexistente, falta um error handler para tratar isso

3 - Mesma coisa envia um usuário sem informar algum campo, poderia ser um 400 bad request se possível com a mensagem que ele expõe no log de campo não pode ser nulo

**Comment by PauloGascho** [comment]
- [x] 1 - Recomendação utilizar sempre o parâmetro de referência como primeiro parâmetro, no caso id do usuário e aí o objeto de update
- [x] 2 - Tua rota de get por id não retorna 404 quando informa um id inexistente, falta um error handler para tratar isso
- [x] 3 - Mesma coisa envia um usuário sem informar algum campo, poderia ser um 400 bad request se possível com a mensagem que ele expõe no log de campo não pode ser nulo
