### ISSUE TITLE
Detalhes e sugestões

### ISSUE THREAD

**Issue by luisfelipecunhaduarte** [PauloGascho/cleanarch-crud#2]
https://github.com/PauloGascho/cleanarch-crud/blob/5601b3b3fbe2f887023ac415e6759f190d512604/usecases/src/main/java/br/com/almode/cleanarch/usecases/usecases/usuario/DeleteUsuarioUseCase.java#L16

1 - Rotas de delete normalmente são void

**Comment by germanyn** [comment]
Isso é outro detalhe que eu induzi eles, geralmente são void, mas eu dou preferência a haver o retorno do que foi excluído
